### ISSUE TITLE
Make JSON request safe

### ISSUE THREAD

**Issue by JaFi-cz** [tinyBigGAMES/AskChatGPT#3]
Add this function (or analogical) and call it before request to make JSON request safe:
```
function MakeJsonSafe(const AStr: string): string;
var
  i: Integer;
begin
  Result := '';
  for i := 1 to Length(AStr) do
  begin
    case AStr[i] of
      '\': Result := Result + '\\';
      '"': Result := Result + '\"';
      '/': Result := Result + '\/';
      #8:  Result := Result + '\b';
      #9:  Result := Result + '\t';
      #10: Result := Result + '\n';
      #12: Result := Result + '\f';
      #13: Result := Result + '\r';
      else
        Result := Result + AStr[i];
    end;
  end;
  Result := Result;
end;

```

**Comment by jarroddavis68** [comment]
Hi sweet. Thanks for this contribution. 

When I plug this in, I get the following response:

```We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)```

before: `{"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"what is kno3"}]}`

after: `{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"user\",\"content\":\"what is kno3\"}]}`

**Comment by JaFi-cz** [comment]
Hello
call this function in the SetQuestion(), not for whole JSON. 
It replaces your 3 chars invalid characters with all JSON chars you have to escape

**Comment by jarroddavis68** [comment]
Ahh, gotcha.
