### ISSUE TITLE
I am not going to buy a new Delphi

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/AskChatGPT#6]
cannot compile 10.2.3

**Comment by JaFi-cz** [comment]
What is your error message?

**Comment by limelect** [comment]
[dcc64 Error] AskChatGPT.pas(293): E2003 Undeclared identifier: 'P'
[dcc64 Error] AskChatGPT.pas(293): E2066 Missing operator or semicolon
[dcc64 Error] AskChatGPT.pas(299): E2362 Cannot access protected symbol TJSONObject.FindValue
[dcc64 Error] AskChatGPT.pas(299): E2015 Operator not applicable to this operand type
[dcc64 Error] AskChatGPT.pas(301): E2003 Undeclared identifier: 'P'
[dcc64 Error] AskChatGPT.pas(301): E2066 Missing operator or semicolon
[dcc64 Fatal Error] uTestbed.pas(87): F2063 Could not compile used unit 'AskChatGPT.pas'
Failed

**Comment by limelect** [comment]
I guess it was compiled with newer ver

**Comment by jarroddavis68** [comment]
I just pushed an update, maybe it can compile now?
